### ISSUE TITLE
Upgrading from v3.1.1 breaks registration of authenticators

### ISSUE THREAD

**Issue by exptom** [web-auth/webauthn-framework#129]
We have an implementation that follows the "easy way" example in your documentation. We first deployed this with v3.1.1 of your library.

We defined our composer dependency as `"web-auth/webauthn-lib" : "^3.1"` and had the following packages installed:
```
web-auth/cose-lib                                 v3.1.1        CBOR Object Signing and Encryption...
web-auth/metadata-service                         v3.1.1        Metadata Service for FIDO2/Webauthn
web-auth/webauthn-lib                             v3.1.1        FIDO2/Webauthn Support For PHP
```
Following a composer update the package versions are now:
```
web-auth/cose-lib                                 v3.2.3        CBOR Object Signing and Encryption...
web-auth/metadata-service                         v3.2.3        Metadata Service for FIDO2/Webauthn
web-auth/webauthn-lib                             v3.2.3        FIDO2/Webauthn Support For PHP
```
When attempting to add a new authenticator the following line of code:
```
$publicKeyCredentialSource = $this->getWebauthnServer()->loadAndCheckAttestationResponse(
                $authenticatorResponse,
                $publicKeyCredentialCreationOptions,
                $serverRequest
            );
```
Now results in an exception being thrown:
```
Exception Information

File

    /vagrant/vendor/web-auth/webauthn-lib/src/AttestationStatement/AndroidSafetyNetAttestationStatementSupport.php:73

Message

    The algorithm RS256 is missing. Did you forget to install the package web-token/jwt-signature-algorithm-rsa?

Stack Trace

    #0 /vagrant/vendor/web-auth/webauthn-lib/src/Server.php(296): Webauthn\AttestationStatement\AndroidSafetyNetAttestationStatementSupport->__construct(NULL, NULL, NULL, 2000, 60000)
    #1 /vagrant/vendor/web-auth/webauthn-lib/src/Server.php(224): Webauthn\Server->getAttestationStatementSupportManager()
    #2 /vagrant/vendor/switchsys/zf-mvc-users/src/Service/WebauthnServer.php(134): Webauthn\Server->loadAndCheckAttestationResponse('{"id":"W9nwvN05...', Object(Webauthn\PublicKeyCredentialCreationOptions), Object(Zend\Diactoros\ServerRequest))
    #3 /vagrant/vendor/switchsys/zf-mvc-users/src/Controller/UserEntityWebauthnController.php(196): SwitchSys\ZF\MvcUsers\Service\WebauthnServer->verifyPublicKeyCredentialCreationResponse('{"id":"W9nwvN05...', Object(Zend\Diactoros\ServerRequest))
    #4 /vagrant/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): SwitchSys\ZF\MvcUsers\Controller\UserEntityWebauthnController->addResponseAction()
    #5 /vagrant/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #6 /vagrant/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
    #7 /vagrant/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(106): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #8 /vagrant/vendor/zendframework/zend-mvc/src/DispatchListener.php(138): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #9 /vagrant/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #10 /vagrant/vendor/zendframework/zend-eventmanager/src/EventManager.php(179): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
    #11 /vagrant/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #12 /vagrant/public/index.php(18): Zend\Mvc\Application->run()
    #13 {main}

```

If I manually add the package mention in the exception message then that leads to a further exception.

**Comment by Spomky** [comment]
Hi @exptom,

This should be fixed with ~`v3.2.6`~`v3.2.5`.
Can you check if the error is thrown with this version?

**Comment by exptom** [comment]
Thanks for the quick turnaround on this but 3.2.6 doesn't appear to be available via packagist yet.

**Comment by Spomky** [comment]
Sorry I meant `v3.2.5`

**Comment by exptom** [comment]
I cannot seem to get it to upgrade past `3.2.3`, there seem to be some dependency changes that conflict with other packages and packagist cannot resolve to an installable set of dependencies.

**Comment by Spomky** [comment]
There are changes between [v3.2.3 and v3.2.4](https://github.com/web-auth/webauthn-framework/compare/v3.2.3...v3.2.4) regarding the dependencies.

The main change is [`beberlei/assert`](https://packagist.org/packages/beberlei/assert) from `^3.0` to `^3.2`, but this modification does not add any other deps.

Can you try to force `^3.2.5` in your composer file and try `composer update`?
The error you will receive will help me to understand what package is creating a conflict

**Comment by exptom** [comment]
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - switchsys/zf-mvc-default-frontend 1.7.3 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.7.5 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.7.1 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.6.0 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.7.7 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.5.0 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.1.0 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.0.0 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.2.0 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.3.1 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.6.1 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.4.0 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.6.2 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.3.2 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.3.0 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.7.2 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.7.6 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.7.4 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - switchsys/zf-mvc-default-frontend 1.7.0 requires php ^5.6 -> your PHP version (7.2.30) does not satisfy that requirement.
    - Conclusion: remove switchsys/zf-mvc-default-frontend 1.10.5
    - Conclusion: don't install switchsys/zf-mvc-default-frontend 1.10.5
    - Conclusion: don't install symfony/process v5.0.8
    - Conclusion: remove kriswallsmith/assetic 1.4.0.1|install symfony/process v5.0.8
    - Installation request for web-auth/webauthn-lib 3.2.5 -> satisfiable by web-auth/webauthn-lib[v3.2.5].
    - switchsys/zf-mvc-default-frontend 1.9.1 requires kriswallsmith/assetic 1.4.0.1 -> satisfiable by kriswallsmith/assetic[1.4.0.1].
    - switchsys/zf-mvc-default-frontend 1.10.4 requires kriswallsmith/assetic 1.4.0.1 -> satisfiable by kriswallsmith/assetic[1.4.0.1].
    - switchsys/zf-mvc-default-frontend 1.10.0 requires kriswallsmith/assetic 1.4.0.1 -> satisfiable by kriswallsmith/assetic[1.4.0.1].
    - switchsys/zf-mvc-default-frontend 1.9.0 requires kriswallsmith/assetic 1.4.0.1 -> satisfiable by kriswallsmith/assetic[1.4.0.1].
    - switchsys/zf-mvc-default-frontend 1.10.3 requires kriswallsmith/assetic 1.4.0.1 -> satisfiable by kriswallsmith/assetic[1.4.0.1].
    - switchsys/zf-mvc-default-frontend 1.8.0 requires kriswallsmith/assetic 1.4.0.1 -> satisfiable by kriswallsmith/assetic[1.4.0.1].
    - switchsys/zf-mvc-default-frontend 1.10.2 requires kriswallsmith/assetic 1.4.0.1 -> satisfiable by kriswallsmith/assetic[1.4.0.1].
    - switchsys/zf-mvc-default-frontend 1.0.x-dev requires kriswallsmith/assetic 1.4.0.1 -> satisfiable by kriswallsmith/assetic[1.4.0.1].
    - switchsys/zf-mvc-default-frontend 1.10.1 requires kriswallsmith/assetic 1.4.0.1 -> satisfiable by kriswallsmith/assetic[1.4.0.1].
    - Conclusion: don't install kriswallsmith/assetic 1.4.0.1
    - Installation request for switchsys/zf-mvc-default-frontend ^1.0 -> satisfiable by switchsys/zf-mvc-default-frontend[1.7.0, 1.10.1, 1.7.4, 1.7.6, 1.7.2, 1.0.x-dev, 1.3.0, 1.3.2, 1.6.2, 1.4.0, 1.6.1, 1.10.2, 1.3.1, 1.8.0, 1.10.3, 1.2.0, 1.9.0, 1.0.0, 1.1.0, 1.5.0, 1.7.7, 1.10.5, 1.6.0, 1.7.1, 1.7.5, 1.10.0, 1.10.4, 1.7.3, 1.9.1].
```
`switchsys/zf-mvc-default-frontend` is one of our internal packages which has a dependency on `kriswallsmith/assetic` which it looks like has a problem with the `symfony/process` dependency.

**Comment by Spomky** [comment]
Thank you.

The problem comes from `kriswallsmith/assetic` that requires `"symfony/process": "~2.1|~3.0"`.

[`symfony/process`](https://github.com/web-auth/webauthn-framework/compare/v3.2.3...v3.2.4#diff-6db1befc15bf0ed55836b4407a7db5e0R31) was missing from the lib package.
Assetic looks to be abandonned (no commit for mors than 3 years).
As a quick resolution I think I can allow symfony process ^3.0 without any problem (to be confirmed), but from my point of view your project should migrate that dep to a more modern lib to manage assets (e.g. [the asset component](https://symfony.com/doc/current/components/asset.html) or [webpack](https://symfony.com/doc/current/frontend.html))

**Comment by Spomky** [comment]
`v3.2.6` allows `symfony/process: "^3.0"`. You should now be able to update the library.

**Comment by exptom** [comment]
@Spomky Thanks for all your help. I can confirm that `v3.2.6` is installable and resolves the issue that I originally reported.
