### ISSUE TITLE
Invalid User Handle

### ISSUE THREAD

**Issue by AlexHaible** [web-auth/webauthn-framework#390]
### Version(s) affected

4.5.1

### Description

I'm getting this error whenever a user is trying to authenticate via a 2nd platform after registering via an Android phone. I personally never experienced any issues, as I started registered from an iPhone, and all subsequent auths have worked flawlessly.

The repo in question is publicly available here: https://github.com/AlexHaible/Gettin-Flippy-With-It

```
production.ERROR: Invalid user handle {"exception":"[object] (Webauthn\\Exception\\AuthenticatorResponseVerificationException(code: 0): Invalid user handle at /home/forge/cinema.alex.quest/vendor/web-auth/webauthn-lib/src/Exception/AuthenticatorResponseVerificationException.php:13)
[stacktrace]
#0 /home/forge/cinema.alex.quest/vendor/web-auth/webauthn-lib/src/AuthenticatorAssertionResponseValidator.php(149): Webauthn\\Exception\\AuthenticatorResponseVerificationException::create()
#1 /home/forge/cinema.alex.quest/app/Http/Controllers/AuthenticationController.php(148): Webauthn\\AuthenticatorAssertionResponseValidator->check()
#2 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\AuthenticationController->verify()
#3 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#4 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#5 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#6 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Routing\\Route->run()
#7 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#8 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#9 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#10 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#11 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#12 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#14 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest()
#16 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle()
#17 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#19 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#21 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(797): Illuminate\\Pipeline\\Pipeline->then()
#23 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(776): Illuminate\\Routing\\Router->runRouteWithinStack()
#24 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(740): Illuminate\\Routing\\Router->runRoute()
#25 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Routing/Router.php(729): Illuminate\\Routing\\Router->dispatchToRoute()
#26 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#27 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#28 /home/forge/cinema.alex.quest/vendor/livewire/livewire/src/DisableBrowserCache.php(19): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\\DisableBrowserCache->handle()
#30 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#31 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#32 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#33 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#35 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#36 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#38 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#40 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#42 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#44 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#46 /home/forge/cinema.alex.quest/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#47 /home/forge/cinema.alex.quest/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle()
#48 {main}
"} 
```

### How to reproduce

Now I don't have this as first-hand steps, but according to the user in question, this is what he did.

1. Register with Android phone.
2. Try authing on other device
3. Go through auth process, and get error after authing.

**Comment by AlexHaible** [comment]
Doing a bit more digging, it appears that $responseUserHandle here https://github.com/web-auth/webauthn-framework/blob/67c32915860aa3e84bb7c17a539a49078fb138ed/src/webauthn/src/AuthenticatorAssertionResponseValidator.php#L138 is null, for some reason.

**Comment by Spomky** [comment]
Hi,

As I mentioned in https://github.com/web-auth/webauthn-framework/issues/362#issuecomment-1399271904, if the user handle is not set in the authenticator response, this means the authenticator cannot discover the public key. You have to ask the user for its username and pass the user handle (i.e. the user ID as fifth argument of the `check` method.

**Comment by AlexHaible** [comment]
Ha! That did the trick. Supplying the username the user provided to even do the login with a null coalescing operator was enough to get it workin' properly. Nice!
