### ISSUE TITLE
PublicKeyCredentialUserEntity::createFromArray uses wrong base64 decoder

### ISSUE THREAD

**Issue by arokettu** [web-auth/webauthn-framework#540]
### Version(s) affected

4.7.7

### Description

PublicKeyCredentialUserEntity::createFromArray uses wrong base64 decoder

### How to reproduce

```php
<?php

use Webauthn\PublicKeyCredentialUserEntity;

require __DIR__ . '/../vendor/autoload.php';

$ue = new PublicKeyCredentialUserEntity("test test", "\0\1\2\xff", "test test");
$ue2 = PublicKeyCredentialUserEntity::createFromString(json_encode($ue));
// Base64::decode() only expects characters in the correct base64 alphabet in .../paragonie/constant_time_encoding/src/Base64.php:219
// #0 .../web-auth/webauthn-lib/src/PublicKeyCredentialUserEntity.php(72): ParagonIE\ConstantTime\Base64::decode()
// #1 .../web-auth/webauthn-lib/src/PublicKeyCredentialUserEntity.php(55): Webauthn\PublicKeyCredentialUserEntity::createFromArray()
// #2 debug.php(8): Webauthn\PublicKeyCredentialUserEntity::createFromString()
```

### Possible Solution

I guess it should use \Webauthn\Util\Base64 instead of \ParagonIE\ConstantTime\Base64

**Comment by Spomky** [comment]
Hi,

Indeed, there is something wrong with the encoding/decoding process.
I will fix it ASAP.

Regards.

**Comment by arokettu** [comment]
Can I speed it up by a MR?

**Comment by Spomky** [comment]
Hi,

It is now fixed in the last bug release.

Regards.

**Comment by arokettu** [comment]
Seems working, thanks
